[functions]

# Where your serverless functions live (relative to repo root)
directory = "functions"

# Ensures proper bundling for Node deps like Prisma
node_bundler = "esbuild"


[[redirects]]

from = "/api/*"
to = "https://auth-guarded-hub-api.netlify.app/.netlify/functions/health/:splat"
status = 200
force = true