[functions]

# Where your serverless functions live (relative to repo root)
directory = "netlify/functions"

# Ensures proper bundling for Node deps like Prisma
node_bundler = "esbuild"


[[redirects]]

# dev & prod: FE calls /api/*, Netlify maps to functions
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true


# SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200