name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        fetch-depth: 0 # full git history
        persist-credentials: true # keep GITHUB_TOKEN configured

      - name: Setup Node.js & pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Build & Publish UI package
        id: changesets
        uses: changesets/action@v1
        with:
          # Commit straight back to main instead of opening a PR
          publish: pnpm release
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
